# Version should be what `git describe --tags` gives you at the `commit`
{% set version = "0.3.0.136.g511453a" %}
{% set commit = "511453a19ebcf21d15879bcbdc65b266cf07120d" %}

package:
  name: python-symengine
  version: {{ version }}

source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/symengine/symengine.py/archive/{{ commit }}.tar.gz

build:
  number: 1
  skip: true        # [win and py<35]
  features:
    - vc14          # [win and py>=35]

requirements:
  build:
    - toolchain
    - cmake
    - symengine     0.3.0.430.gb3a2159
    - python
    - cython
    - setuptools
    - llvmdev       >=3.9
    - gmp           6.*     # [unix]
    - mpir          3.*     # [win]
    - mpfr          4.*
    - mpc           1.*
    - libflint      2.5.*   # [unix]
  run:
    - symengine     0.3.0.430.gb3a2159
    - python
    - numpy
    - gmp           6.*     # [unix]
    - mpir          3.*     # [win]
    - mpfr          4.*
    - mpc           1.*
    - libflint      2.5.*   # [unix]

test:
  requires:
    - pytest
    - sympy
  imports:
    - symengine
  commands:
    - python -c $'import symengine;\nif not symengine.test():\n raise Exception("Tests failed")'    # [unix]

about:
  home: https://github.com/symengine/symengine.py
  license: MIT
  license_file: LICENSE
  summary: 'Python wrappers for SymEngine, a fast symbolic manipulation library, written in C++'

extra:
  recipe-maintainers:
    - isuruf
    - certik
